import {randomUUID} from "node:crypto";import {pool} from "@/lib/postgres";import type {Advisor} from "./contracts";import {buildExecutiveEvidence} from "./evidence";import {generateExecutiveAdvice} from "./provider";import {validateExecutiveAdvice} from "./validation";
export async function runExecutiveAdvisor(organizationId:string,userId:string,advisor:Advisor){
  const evidence=await buildExecutiveEvidence(organizationId,advisor),runId=randomUUID();
  await pool.query(`INSERT INTO executive_ai_runs(id,organization_id,advisor,status,evidence_snapshot,evidence_hash,prompt_version,schema_version,requested_by) VALUES($1,$2,$3,'pending',$4,$5,'executive-advisor-v1','executive-output-v1',$6)`,[runId,organizationId,advisor,JSON.stringify({catalog:evidence.catalog,sourceWatermark:evidence.sourceWatermark}),evidence.evidenceHash,userId]);
  try{
    if(!evidence.catalog.length)throw Object.assign(new Error("No warehouse evidence is available for this advisor."),{code:"insufficient_evidence"});
    await pool.query(`UPDATE executive_ai_runs SET status='generating' WHERE id=$1`,[runId]);
    const generated=await generateExecutiveAdvice({advisor,evidence:evidence.catalog}),output=validateExecutiveAdvice(generated.output,evidence.catalog);
    const client=await pool.connect();try{await client.query("BEGIN");for(const item of output.recommendations)await client.query(`INSERT INTO executive_ai_recommendations(id,run_id,priority,title,recommendation,rationale,evidence_refs,risks) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[randomUUID(),runId,item.priority,item.title,item.recommendation,item.rationale,JSON.stringify(item.evidenceRefs),JSON.stringify(item.risks)]);await client.query(`UPDATE executive_ai_runs SET status='completed',provider=$2,model=$3,usage_metadata=$4,summary=$5,limitations=$6,completed_at=NOW() WHERE id=$1`,[runId,generated.provider,generated.model,JSON.stringify(generated.usage),output.summary,JSON.stringify(output.limitations)]);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
    return {runId,status:"completed" as const,summary:output.summary,limitations:output.limitations,recommendations:output.recommendations};
  }catch(error){const code=(error as {code?:string}).code||(/evidence|malformed/.test(error instanceof Error?error.message:"")?"invalid_evidence_output":"provider_failure");await pool.query(`UPDATE executive_ai_runs SET status='failed',safe_error_code=$2,safe_error_message=$3,completed_at=NOW() WHERE id=$1`,[runId,code,code==="missing_api_key"?"Executive AI is not configured.":code==="insufficient_evidence"?"No warehouse evidence is available for this advisor.":"Executive advice could not be generated safely."]);throw Object.assign(new Error(code==="missing_api_key"?"Executive AI is not configured.":code==="insufficient_evidence"?"No warehouse evidence is available for this advisor.":"Executive advice could not be generated safely."),{code,runId});}
}
export async function listExecutiveRuns(organizationId:string){return (await pool.query(`SELECT r.id,r.advisor,r.status,r.provider,r.model,r.summary,r.limitations,r.safe_error_code AS "safeErrorCode",r.created_at AS "createdAt",r.completed_at AS "completedAt",COALESCE(JSON_AGG(JSON_BUILD_OBJECT('id',x.id,'priority',x.priority,'title',x.title,'recommendation',x.recommendation,'rationale',x.rationale,'evidenceRefs',x.evidence_refs,'risks',x.risks,'status',x.status)) FILTER(WHERE x.id IS NOT NULL),'[]') recommendations FROM executive_ai_runs r LEFT JOIN executive_ai_recommendations x ON x.run_id=r.id WHERE r.organization_id=$1 GROUP BY r.id ORDER BY r.created_at DESC LIMIT 50`,[organizationId])).rows;}
