import {randomUUID} from "node:crypto";import type {PoolClient} from "pg";
export async function refreshDimensions(client:PoolClient,organizationId:string,watermark:Date){
  let rows=0;
  await client.query(`INSERT INTO warehouse_dim_date(date_key,calendar_date,day_of_week,week_of_year,month_number,quarter_number,year_number,is_weekend)
    SELECT TO_CHAR(day,'YYYYMMDD')::int,day::date,EXTRACT(ISODOW FROM day)::int,EXTRACT(WEEK FROM day)::int,EXTRACT(MONTH FROM day)::int,EXTRACT(QUARTER FROM day)::int,EXTRACT(YEAR FROM day)::int,EXTRACT(ISODOW FROM day) IN (6,7)
    FROM GENERATE_SERIES((CURRENT_DATE-INTERVAL '10 years')::date,(CURRENT_DATE+INTERVAL '2 years')::date,INTERVAL '1 day') day ON CONFLICT DO NOTHING`);
  const businesses=await client.query(`SELECT b.id,b.name,b.domain,COALESCE(b.country,'Unknown') region,COALESCE(b.niche,'general') industry,b.status,COALESCE(b.created_at,NOW()) source_updated_at FROM businesses b JOIN crm_accounts a ON a.business_id=b.id WHERE a.organization_id=$1`,[organizationId]);
  for(const item of businesses.rows){const current=await client.query(`SELECT id,name,normalized_domain,region,industry,status FROM warehouse_dim_business WHERE organization_id=$1 AND business_id=$2 AND is_current FOR UPDATE`,[organizationId,item.id]);const changed=!current.rowCount||["name","normalized_domain","region","industry","status"].some(key=>String(current.rows[0][key])!==String(key==="normalized_domain"?item.domain.toLowerCase():item[key]));if(changed){await client.query(`UPDATE warehouse_dim_business SET is_current=FALSE,valid_to=$3 WHERE organization_id=$1 AND business_id=$2 AND is_current`,[organizationId,item.id,watermark]);await client.query(`INSERT INTO warehouse_dim_business(id,organization_id,business_id,name,normalized_domain,region,industry,status,valid_from,source_updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[randomUUID(),organizationId,item.id,item.name,item.domain.toLowerCase(),item.region,item.industry,item.status,watermark,item.source_updated_at]);rows++;}}
  const users=await client.query(`SELECT u.id,r.code role_code,u.status FROM enterprise_memberships m JOIN enterprise_users u ON u.id=m.user_id JOIN enterprise_roles r ON r.id=m.role_id WHERE m.organization_id=$1`,[organizationId]);
  for(const item of users.rows){const current=await client.query(`SELECT id,role_code,status FROM warehouse_dim_user WHERE organization_id=$1 AND user_id=$2 AND is_current FOR UPDATE`,[organizationId,item.id]);if(!current.rowCount||current.rows[0].role_code!==item.role_code||current.rows[0].status!==item.status){await client.query(`UPDATE warehouse_dim_user SET is_current=FALSE,valid_to=$3 WHERE organization_id=$1 AND user_id=$2 AND is_current`,[organizationId,item.id,watermark]);await client.query(`INSERT INTO warehouse_dim_user(id,organization_id,user_id,role_code,status,valid_from) VALUES($1,$2,$3,$4,$5,$6)`,[randomUUID(),organizationId,item.id,item.role_code,item.status,watermark]);rows++;}}
  const plans=await client.query(`SELECT id,code,name,monthly_price_minor,currency FROM billing_plans`);
  for(const item of plans.rows){if(!(await client.query(`SELECT 1 FROM warehouse_dim_plan WHERE plan_id=$1 AND is_current`,[item.id])).rowCount){await client.query(`INSERT INTO warehouse_dim_plan(id,plan_id,code,name,monthly_price_minor,currency,valid_from) VALUES($1,$2,$3,$4,$5,$6,$7)`,[randomUUID(),item.id,item.code,item.name,item.monthly_price_minor,item.currency,watermark]);rows++;}}
  const stages=await client.query(`SELECT p.id pipeline_id,p.name pipeline_name,s.id stage_id,s.name stage_name,s.position stage_position,s.probability_basis_points,s.is_closed,s.is_won FROM crm_pipelines p JOIN crm_pipeline_stages s ON s.pipeline_id=p.id WHERE p.organization_id=$1`,[organizationId]);
  for(const item of stages.rows){if(!(await client.query(`SELECT 1 FROM warehouse_dim_pipeline WHERE organization_id=$1 AND stage_id=$2 AND is_current`,[organizationId,item.stage_id])).rowCount){await client.query(`INSERT INTO warehouse_dim_pipeline(id,organization_id,pipeline_id,stage_id,pipeline_name,stage_name,stage_position,probability_basis_points,is_closed,is_won,valid_from) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[randomUUID(),organizationId,item.pipeline_id,item.stage_id,item.pipeline_name,item.stage_name,item.stage_position,item.probability_basis_points,item.is_closed,item.is_won,watermark]);rows++;}}
  return rows;
}
