"use client";
import Link from "next/link";
import { useState,type FormEvent } from "react";

export default function AuthForm(){
  const [mode,setMode]=useState<"login"|"register">("login"),[status,setStatus]=useState(""),[busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){
    event.preventDefault();setBusy(true);setStatus("");
    const data=new FormData(event.currentTarget);
    const body=mode==="login"?{email:data.get("email"),password:data.get("password"),...(data.get("mfaCode")?{mfaCode:data.get("mfaCode")}:{})}:{email:data.get("email"),password:data.get("password"),displayName:data.get("displayName"),organizationName:data.get("organizationName")};
    try{const response=await fetch(`/api/auth/${mode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Authentication failed.");window.location.assign("/crm");}catch(error){setStatus(error instanceof Error?error.message:"Authentication failed.");}finally{setBusy(false);}
  }
  return <div className="mx-auto max-w-lg rounded-3xl border border-white/[.09] bg-white/[.035] p-6 sm:p-8"><div className="mb-6 flex rounded-xl bg-black/20 p-1"><button onClick={()=>setMode("login")} className={`flex-1 rounded-lg px-3 py-2 text-sm font-bold ${mode==="login"?"bg-cyan-300 text-slate-950":"text-slate-400"}`}>Sign in</button><button onClick={()=>setMode("register")} className={`flex-1 rounded-lg px-3 py-2 text-sm font-bold ${mode==="register"?"bg-cyan-300 text-slate-950":"text-slate-400"}`}>Create organization</button></div><form onSubmit={submit} className="space-y-4">{mode==="register"&&<><Field name="displayName" label="Your name"/><Field name="organizationName" label="Organization"/></>}<Field name="email" label="Email" type="email"/><Field name="password" label="Password" type="password"/>{mode==="login"&&<Field name="mfaCode" label="MFA code (when enabled)" required={false}/>}<button disabled={busy} className="w-full rounded-xl bg-cyan-300 px-4 py-3 text-sm font-black text-slate-950 disabled:opacity-50">{busy?"Working…":mode==="login"?"Sign in securely":"Create secure workspace"}</button>{status&&<p role="alert" className="text-sm text-rose-300">{status}</p>}</form><div className="mt-6 grid gap-2 sm:grid-cols-2"><Link href="/api/auth/oauth/google/start" className="rounded-xl border border-white/10 px-3 py-2 text-center text-xs font-bold text-slate-300">Continue with Google</Link><Link href="/api/auth/oauth/microsoft/start" className="rounded-xl border border-white/10 px-3 py-2 text-center text-xs font-bold text-slate-300">Continue with Microsoft</Link></div></div>;
}
function Field({name,label,type="text",required=true}:{name:string;label:string;type?:string;required?:boolean}){return <label className="block text-sm font-semibold text-slate-300">{label}<input name={name} type={type} required={required} minLength={type==="password"?12:undefined} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-3 text-white outline-none focus:border-cyan-300"/></label>}
