"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { ArrowUpRight, Database, LoaderCircle } from "lucide-react";

export default function EnterpriseRecords({endpoint,collection,empty}:{endpoint:string;collection:string;empty:string}){
  const [rows,setRows]=useState<Record<string,unknown>[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{fetch(endpoint,{credentials:"same-origin"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(response.status===401?"Authentication required.":body.error||"Data unavailable.");const value=body[collection]??body.data??[];setRows(Array.isArray(value)?value:[]);}).catch(reason=>setError(reason instanceof Error?reason.message:"Data unavailable.")).finally(()=>setLoading(false));},[endpoint,collection]);
  if(loading)return <div className="grid h-52 place-items-center rounded-[2rem] border border-white/[.07] bg-white/[.025]" aria-label="Loading enterprise records"><LoaderCircle className="size-6 animate-spin text-orange-300"/></div>;
  if(error)return <div role="alert" className="rounded-[2rem] border border-amber-300/20 bg-amber-300/[.05] p-6 text-sm text-amber-100">{error} {error.includes("Authentication")&&<Link className="ml-2 font-bold text-orange-300" href="/login">Sign in</Link>}</div>;
  if(!rows.length)return <div role="status" className="rounded-[2rem] border border-dashed border-white/[.12] bg-white/[.025] p-10 text-center"><Database className="mx-auto size-7 text-slate-600"/><strong className="mt-4 block text-base text-white">No records yet</strong><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-500">{empty}</p></div>;
  return <section className="overflow-hidden rounded-[2rem] border border-white/[.08] bg-white/[.025]"><div className="flex items-center justify-between border-b border-white/[.07] px-5 py-4"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-orange-300">Live workspace data</p><h2 className="mt-1 text-sm font-bold text-white">{rows.length} {rows.length===1?"record":"records"}</h2></div><Database className="size-5 text-slate-600"/></div><ul className="divide-y divide-white/[.06]">{rows.map((row,index)=><li key={String(row.id??index)} className="group grid gap-3 px-5 py-4 transition hover:bg-white/[.025] sm:grid-cols-[auto_1fr_auto] sm:items-center"><span className="grid size-9 place-items-center rounded-xl bg-orange-300/[.07] text-xs font-black text-orange-300">{String(index+1).padStart(2,"0")}</span><div><strong className="text-sm text-white">{String(row.name??row.title??row.jobType??row.metric??`Record ${index+1}`)}</strong><p className="mt-1 text-xs capitalize text-slate-500">{String(row.domain??row.stage??row.status??row.priority??"Recorded")}</p></div><div className="flex items-center gap-3 text-xs text-slate-500"><span>{formatDate(row.updatedAt??row.createdAt??row.dueAt)}</span><ArrowUpRight className="size-4 text-slate-700 transition group-hover:text-orange-300"/></div></li>)}</ul></section>;
}
function formatDate(value:unknown){if(!value)return "";const date=new Date(String(value));return Number.isNaN(date.valueOf())?"":date.toLocaleDateString();}
