import {randomUUID} from "node:crypto";import type {PoolClient} from "pg";import {pool} from "@/lib/postgres";import {granularities} from "../contracts";import {periodBounds} from "../aggregations/periods";import {refreshDimensions} from "../dimensions";import {refreshFacts} from "../facts";import {calculateMetrics} from "../metrics/catalog";
async function refreshSnapshots(client:PoolClient,organizationId:string,watermark:Date){
  let rows=0;
  for(const granularity of granularities){const {start,end}=periodBounds(granularity,watermark);const metrics=await calculateMetrics(client,organizationId,start,end);for(const metric of metrics){await client.query(`INSERT INTO warehouse_metric_snapshots(id,organization_id,dashboard,metric,period_granularity,period_start,period_end,value_numeric,value_text,currency,evidence,source_watermark) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(organization_id,dashboard,metric,period_granularity,period_start) DO UPDATE SET period_end=EXCLUDED.period_end,value_numeric=EXCLUDED.value_numeric,value_text=EXCLUDED.value_text,currency=EXCLUDED.currency,evidence=EXCLUDED.evidence,calculated_at=NOW(),source_watermark=EXCLUDED.source_watermark`,[randomUUID(),organizationId,metric.dashboard,metric.metric,granularity,start,end,metric.valueNumeric,metric.valueText,metric.currency,JSON.stringify(metric.evidence),watermark]);rows++;}}
  return rows;
}
export async function refreshWarehouse(organizationId:string){
  const client=await pool.connect(),runId=randomUUID(),watermark=new Date();
  try{await client.query("BEGIN");await client.query(`INSERT INTO warehouse_refresh_runs(id,organization_id,status,source_watermark) VALUES($1,$2,'running',$3)`,[runId,organizationId,watermark]);const dimensionRows=await refreshDimensions(client,organizationId,watermark);const factRows=await refreshFacts(client,organizationId);const snapshotRows=await refreshSnapshots(client,organizationId,watermark);const rowsWritten=dimensionRows+factRows+snapshotRows;await client.query(`UPDATE warehouse_refresh_runs SET status='completed',completed_at=NOW(),rows_written=$2 WHERE id=$1`,[runId,rowsWritten]);await client.query("COMMIT");return {runId,status:"completed" as const,rowsWritten,sourceWatermark:watermark.toISOString()};}
  catch(error){await client.query("ROLLBACK");await pool.query(`INSERT INTO warehouse_refresh_runs(id,organization_id,status,source_watermark,completed_at,safe_error_code,safe_error_message) VALUES($1,$2,'failed',$3,NOW(),'refresh_failed',$4) ON CONFLICT(id) DO NOTHING`,[runId,organizationId,watermark,error instanceof Error?error.message.slice(0,500):"Warehouse refresh failed."]);throw error;}finally{client.release();}
}
