"use client";import Link from "next/link";import {useEffect,useState} from "react";
type Metric={metric:string;valueNumeric:number|null;valueText:string|null;currency:string|null;evidence:unknown[];periodStart:string;periodEnd:string};
export default function ExecutiveDashboard({dashboard}:{dashboard:"executive"|"sales"|"marketing"|"operations"|"security"}){
  const [data,setData]=useState<{metrics:Metric[];status:string;lastRefresh:string|null}>({metrics:[],status:"loading",lastRefresh:null}),[error,setError]=useState("");
  useEffect(()=>{fetch(`/api/executive/${dashboard}?granularity=monthly`).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(response.status===401?"Authentication required.":body.error||"Analytics unavailable.");setData(body);}).catch(reason=>setError(reason instanceof Error?reason.message:"Analytics unavailable."));},[dashboard]);
  if(error)return <div role="alert" className="rounded-3xl border border-amber-300/20 bg-amber-300/[.05] p-6 text-sm text-amber-100">{error}{error.includes("Authentication")&&<Link href="/login" className="ml-2 font-bold text-cyan-300">Sign in</Link>}</div>;
  if(data.status==="loading")return <div className="grid animate-pulse gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:8}).map((_,index)=><div key={index} className="h-32 rounded-2xl bg-white/[.05]"/>)}</div>;
  if(data.status==="empty")return <div className="rounded-3xl border border-white/[.08] bg-white/[.03] p-8 text-sm text-slate-400">No warehouse snapshot exists. An authorized operator must run an explicit warehouse refresh. No substitute KPIs are shown.</div>;
  return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{data.metrics.map(metric=><article key={metric.metric} className="rounded-2xl border border-white/[.07] bg-white/[.03] p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{metric.metric.replaceAll("_"," ")}</p><strong className="mt-4 block text-2xl font-black text-white">{formatMetric(metric)}</strong><p className="mt-3 text-[11px] text-slate-600">{metric.evidence.length?`${metric.evidence.length} evidence source(s)`:"No connected evidence"}</p></article>)}</div><p className="mt-5 text-xs text-slate-600">Monthly snapshot · refreshed {data.lastRefresh?new Date(data.lastRefresh).toLocaleString():"unknown"}</p></>;
}
function formatMetric(metric:Metric){if(metric.valueText)return metric.valueText;if(metric.valueNumeric===null)return "Unavailable";if(metric.currency)return new Intl.NumberFormat("en-US",{style:"currency",currency:metric.currency,maximumFractionDigits:0}).format(metric.valueNumeric/100);if(/rate|retention|churn/.test(metric.metric))return `${metric.valueNumeric}%`;return new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(metric.valueNumeric);}
